import { Octokit } from "@octokit/rest";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

function getRepo() {
  const repository = process.env.GITHUB_REPOSITORY;
  if (!repository) throw new Error("GITHUB_REPOSITORY not set");
  const [owner, repo] = repository.split("/");
  return { owner, repo };
}

export async function getIssue(issueNumber: number) {
  const { owner, repo } = getRepo();
  const { data } = await octokit.issues.get({
    owner,
    repo,
    issue_number: issueNumber,
  });
  return { title: data.title, body: data.body || "" };
}

export async function listRepoFiles(): Promise<string[]> {
  const { owner, repo } = getRepo();
  try {
    const { data } = await octokit.git.getTree({
      owner,
      repo,
      tree_sha: "HEAD",
      recursive: "true",
    });
    return data.tree
      .filter((item) => item.type === "blob")
      .map((item) => item.path!);
  } catch {
    return [];
  }
}

export async function createBranch(branchName: string): Promise<void> {
  const { owner, repo } = getRepo();

  // Get the SHA of the default branch
  const { data: ref } = await octokit.git.getRef({
    owner,
    repo,
    ref: "heads/main",
  });

  // Create the new branch
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: ref.object.sha,
  });
}

export async function commitFile(
  branchName: string,
  filePath: string,
  content: string,
  message: string
): Promise<void> {
  const { owner, repo } = getRepo();

  // Get the current commit SHA on the branch
  const { data: ref } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${branchName}`,
  });

  // Get the tree SHA
  const { data: commit } = await octokit.git.getCommit({
    owner,
    repo,
    commit_sha: ref.object.sha,
  });

  // Create a blob
  const { data: blob } = await octokit.git.createBlob({
    owner,
    repo,
    content: Buffer.from(content).toString("base64"),
    encoding: "base64",
  });

  // Create a new tree
  const { data: tree } = await octokit.git.createTree({
    owner,
    repo,
    base_tree: commit.tree.sha,
    tree: [
      {
        path: filePath,
        mode: "100644",
        type: "blob",
        sha: blob.sha,
      },
    ],
  });

  // Create a new commit
  const { data: newCommit } = await octokit.git.createCommit({
    owner,
    repo,
    message,
    tree: tree.sha,
    parents: [ref.object.sha],
  });

  // Update the branch reference
  await octokit.git.updateRef({
    owner,
    repo,
    ref: `heads/${branchName}`,
    sha: newCommit.sha,
  });
}

export async function createPullRequest(
  branchName: string,
  title: string,
  body: string,
  issueNumber: number
): Promise<number> {
  const { owner, repo } = getRepo();

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title,
    body: `${body}\n\nCloses #${issueNumber}\n\n---\n🤖 *Generated by Sukuna IA Developer*`,
    head: branchName,
    base: "main",
  });

  // Add label to identify AI-generated PRs
  await octokit.issues.addLabels({
    owner,
    repo,
    issue_number: pr.number,
    labels: ["ai-developed"],
  });

  return pr.number;
}

export async function getPullRequest(prNumber: number) {
  const { owner, repo } = getRepo();
  const { data } = await octokit.pulls.get({
    owner,
    repo,
    pull_number: prNumber,
  });
  return { title: data.title, body: data.body || "" };
}

export async function getPullRequestDiff(prNumber: number): Promise<string> {
  const { owner, repo } = getRepo();
  const { data } = await octokit.pulls.get({
    owner,
    repo,
    pull_number: prNumber,
    mediaType: { format: "diff" },
  });
  // When requesting diff format, data is returned as a string
  return data as unknown as string;
}

export async function submitReview(
  prNumber: number,
  event: "APPROVE" | "REQUEST_CHANGES" | "COMMENT",
  body: string,
  comments: Array<{ path: string; line: number; body: string }>
): Promise<void> {
  const { owner, repo } = getRepo();

  // Filter valid comments (line > 0)
  const validComments = comments
    .filter((c) => c.line > 0)
    .map((c) => ({
      path: c.path,
      line: c.line,
      body: c.body,
    }));

  await octokit.pulls.createReview({
    owner,
    repo,
    pull_number: prNumber,
    event,
    body: `${body}\n\n---\n🤖 *Reviewed by Sukuna IA Reviewer*`,
    comments: validComments.length > 0 ? validComments : undefined,
  });
}

export async function mergePullRequest(prNumber: number): Promise<void> {
  const { owner, repo } = getRepo();
  await octokit.pulls.merge({
    owner,
    repo,
    pull_number: prNumber,
    merge_method: "squash",
  });
}

export async function commentOnIssue(
  issueNumber: number,
  body: string
): Promise<void> {
  const { owner, repo } = getRepo();
  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body,
  });
}

export async function triggerReview(
  prNumber: number,
  aiProvider: string
): Promise<void> {
  const { owner, repo } = getRepo();
  await octokit.repos.createDispatchEvent({
    owner,
    repo,
    event_type: "ai-review-requested",
    client_payload: {
      pr_number: prNumber,
      ai_provider: aiProvider,
    },
  });
}
